name: flutter_crypto_wallet
description: "A crypto wallet management build with Flutter."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management & routing
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  flow_builder: ^0.0.10

  # Networking
  http: ^1.2.0
  dio: ^5.4.1
  retrofit: ^4.1.0

  # firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.5
  firebase_messaging: ^14.7.16
  firebase_analytics: ^10.8.6
  firebase_crashlytics: ^3.4.15
  google_sign_in: ^6.2.1

  # Themes & Icons & Widgets
  flutter_signin_button: ^2.0.0
  barcode_widget: ^2.0.4

  # Other
  meta: ^1.11.0
  collection: ^1.18.0
  get_it: ^7.6.7
  equatable: ^2.0.5
  formz: ^0.7.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # local
  authentication_repository:
    path: packages/authentication_repository
  form_inputs:
    path: packages/form_inputs

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


  retrofit_generator: ^8.1.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
    - assets/images/icons/crypto_icons/
    - lib/development/coins_response_examples/gecko/

    # example:
    # fonts:
    #   - family: IranSans
    #     fonts:
    #       - asset: fonts/IranSans-Regular.ttf
    #       - asset: fonts/IranSans-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
