name: flutter_crypto_wallet
description: A crypto wallet build with Flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # Networking
  http: ^1.1.2
  dio: ^5.4.0
  retrofit: ^4.0.3

  # firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_messaging: ^14.7.9
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8
  google_sign_in: ^6.2.1

  # Themes & Icons & Widgets
  cupertino_icons: ^1.0.6
  flutter_signin_button: ^2.0.0
  barcode_widget: ^2.0.4

  # Other
  meta: ^1.10.0
  collection: ^1.18.0
  get_it: ^7.6.4
  equatable: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  retrofit_generator: ^8.0.6
  build_runner: ^2.4.7


flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: IranSans
  #     fonts:
  #       - asset: fonts/IranSans-Regular.ttf
  #       - asset: fonts/IranSans-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
